import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { SigninComponent } from './components/signin/signin.component';
import { SignupComponent } from './components/signup/signup.component';
import { UserProfileComponent } from './components/user-profile/user-profile.component';
import { CreateEventoComponent } from './evento/create/create.component';
import { EditEventoComponent } from './evento/edit/edit.component';
import { IndexComponent } from './evento/index/index.component';
import { MineComponent } from './evento/mine/mine.component';
import { ViewEventoComponent } from './evento/view/view.component';
import { IndexCategoriaComponent } from './admin/categorias/index/index.component';
import { CreateCategoriaComponent } from './admin/categorias/create/create.component';
import { EditCategoriaComponent } from './admin/categorias/edit/edit.component';
import { IndexUserComponent } from './admin/user/index/index.component';
import { EditUserComponent } from './admin/user/edit/edit.component';
import { IndexEventoComponent } from './admin/eventos/index/index.component';
import { NosotrosComponent } from './otros/nosotros/nosotros.component';
import { ContactoComponent } from './otros/contacto/contacto.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'login', component: SigninComponent },
  { path: 'register', component: SignupComponent },
  { path: 'profile', component: UserProfileComponent },
  { path: 'evento/create', component: CreateEventoComponent },
  { path: 'evento/edit/:id', component: EditEventoComponent },
  { path: 'evento/index', component: IndexComponent },
  { path: 'evento/mine', component: MineComponent },
  { path: 'evento/view/:id', component: ViewEventoComponent },
  { path: 'about', component: NosotrosComponent },
  { path: 'contacto', component: ContactoComponent },
  { path: 'admin/categoria/index', component: IndexCategoriaComponent },
  { path: 'admin/categoria/create', component: CreateCategoriaComponent },
  { path: 'admin/categoria/edit/:id', component: EditCategoriaComponent },
  { path: 'admin/user/index', component: IndexUserComponent },
  { path: 'admin/user/edit/:id', component: EditUserComponent },
  { path: 'admin/eventos/index', component: IndexEventoComponent },
];
